let fs = require('fs');

let nbLevels = 1;

function transformData(data) {
  
  let res = [];
  let grid = data.levels[0].layerInstances[0].intGrid;

  grid.forEach(_ => {
    res[_.coordId] = _.v;
  });
  return res;
}

function readLevel(level) {
  fs.readFile(`./assets/level${level}.json`, 'utf8', parseLevel(level));
}

function writeFile(path, contents) {
  fs.writeFile(path, contents, (err) => {
    if (err) {
      throw err;
    }
    console.log('done');
  });
}

let levels = [];

function writeLevels() {

  let template = `// Auto generated by levels.js\n`;

  levels.forEach((level, i) => {
    template += `const level${i} = [${level}];\n`;
  });

  template += `\nexport default [\n`;

  levels.forEach((_, i) => {
    template += `level${i},\n`;
  });

  template += `\n];\n`;

  writeFile('src/play/levels.js', template);
}

function parseLevel(level) {
  return (err, contents) => {

    if (err) {
      throw err;
    }

    let data = JSON.parse(contents);

    levels[level] = transformData(data);

    checkWrite();
  };
}

function checkWrite() {
  for (let i = 1; i <= nbLevels; i++) {
    if (!levels[i]) {
      return;
    }
  }

  writeLevels();
};

for (let i = 1; i <= nbLevels; i++) {
  readLevel(i);
}
