let fs = require('fs');

let nbLevels = 1;

function extractLevels(data) {
  return data.levels.map((level, i) => {
    let res = [];
    let grid = level.layerInstances[0].intGrid;

    grid.forEach(_ => {
      res[_.coordId] = _.v;
    });
    return res;
  });
}

function readLevel() {
  fs.readFile(`./assets/level1.json`, 'utf8', parseLevel);
}

function writeFile(path, contents) {
  fs.writeFile(path, contents, (err) => {
    if (err) {
      throw err;
    }
    console.log('done');
  });
}

function writeLevels(levels) {

  let template = `// Auto generated by levels.js\n`;

  levels.forEach((level, i) => {
    template += `const level${i} = [${level}];\n`;
  });

  template += `\nexport default [\n`;

  levels.forEach((_, i) => {
    template += `level${i},\n`;
  });

  template += `\n];\n`;

  writeFile('src/play/levels.js', template);
}

function parseLevel(err, contents) {
  if (err) {
    throw err;
  }

  let data = JSON.parse(contents);

  writeLevels(extractLevels(data));
};



readLevel();
